name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '42 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.1', '3.4' ]
    name: Test with Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Setup Ruby environment
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - run: bundle exec rake unit
        if: always()
      - run: bundle exec rake acceptance
        if: always()
